### ISSUE TITLE
2주차 문제

### ISSUE THREAD

**Issue by Zigje9** [YAPP-19th/Algorithm-Study#7]
# 문제를 댓글로 남겨주세요. 🧐
- 프로그래머스에서 **코틀린**과 **자바스크립트**가 동시에 풀이가 가능한 문제를 추천해주세요!

**Comment by kyoung-jnn** [comment]
월요일 / 예상 대진표 https://programmers.co.kr/learn/courses/30/lessons/12985

**Comment by Zigje9** [comment]
화요일 / 7주차 https://programmers.co.kr/learn/courses/30/lessons/86048?language=javascript

**Comment by ksmfou98** [comment]
수요일 / 괄호변환 https://programmers.co.kr/learn/courses/30/lessons/60058

**Comment by jionchu** [comment]
목요일 / 점프와 순간 이동 https://programmers.co.kr/learn/courses/30/lessons/12980
